VTWebsite/VTWebsite/Controllers/JPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VTWebsite.Models;

namespace VTWebsite.Controllers
{
    public class JPController : Controller
    {
        dbVTEntities db = new dbVTEntities();
        public ActionResult VTDiscovery()
        {
            ViewBag.Message = "Your contact page.";
            var JpallVideo = (from video in db.Video_List
                            join vtuber in db.VTuber_List
                            on video.yt_channel_id equals vtuber.yt_channel_id
                            orderby Guid.NewGuid()
                            select new
                            {
                                video,
                                vtuber
                            }).Take(22740).ToList();

            List<VideoVtuber> model = new List<VideoVtuber>();
            foreach (var item in JpallVideo)
            {
                model.Add(new VideoVtuber()
                {
                    video = item.video,
                    vtuber = item.vtuber
                });

            }
            return View(model);
        }
        public ActionResult DisMuti()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult VTWiki()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult VTWiki_Firm()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult VTWiki_People()
        {
            var people = db.Member_List.ToList();
            ViewBag.Message = "Your contact page.";

            return View(people);
        }
        public ActionResult VTWiki_Members(string id, string org)
        {
            var MemIntro_jp = (from member_jp in db.tMember_jp
                            join intro_jp in db.tIntro_jp
                            on member_jp.tMemberId equals intro_jp.tMemberId
                            select new
                            {
                                member_jp,
                                intro_jp
                            }).ToList();

            List<MembersIntro_jp> model = new List<MembersIntro_jp>();
            foreach (var item in MemIntro_jp)
            {
                model.Add(new MembersIntro_jp()
                {
                    member_jp = item.member_jp,
                    intro_jp = item.intro_jp
                });
                ViewBag.yt_channel_name = id;
                ViewBag.org = org;

            }
            return View(model);
        }
        public ActionResult VTWiki_News()
        {
            var twitter = db.Tweet_List
                .OrderByDescending(m => m.tweet_created_at).ToList();

            ViewBag.Message = "Your contact page.";

            return View(twitter);
        }
        public ActionResult VT_About()
        {
            var todo = db.tToDo_jp
                .OrderByDescending(m => m.fDate).ToList();
            return View(todo);
        }
        public ActionResult VT_Video(string id)
        {

            var JpallVideo = (from video in db.Video_List
                            join vtuber in db.VTuber_List
                            on video.yt_channel_id equals vtuber.yt_channel_id
                            orderby Guid.NewGuid()
                            select new
                            {
                                video,
                                vtuber
                            }).Take(22740).ToList();

            List<VideoVtuber> model = new List<VideoVtuber>();
            foreach (var item in JpallVideo)
            {
                model.Add(new VideoVtuber()
                {
                    video = item.video,
                    vtuber = item.vtuber
                });
                ViewBag.msgv = id;

            }
            return View(model);
        }

        public ActionResult VT_Set()
        {
            return View();
        }
    }
}

VTWebsite/VTWebsite/Views/JP/DisMuti.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/JP/_Layout_DisMuti.cshtml";
}

<title>なまちゅうけい VT_Muti</title>

<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VTWebsite/VTWebsite/Views/JP/VTDiscovery.cshtml
@model IEnumerable<VTWebsite.Models.VideoVtuber>
@{
    Layout = "~/Views/Shared/JP/_Layout_DisIndex.cshtml";
    var n = 0;
    var headn = 0;
}
<html>
<head>
    <meta charset="UTF-8">
    <title>VTDiscovery</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/Content/CustomCSS/PageCss/_FrontPage_VTDis_Main.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@300&display=swap" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="VTDis-title">
        <p>ライブビデオ</p>
    </div>
    <div class="owl-flex">
        <div class="owl-Body">
            <div class="owl-carousel owl-theme">
                @foreach (var item2 in Model.Take(200))
                {
                    if (item2.video.status != "missing" && headn <= 4)
                    {
                        var Videoid2 = @Html.DisplayFor(modelItem => item2.video.yt_video_id).ToString();
                        var Linkvideo2 = "https://www.youtube.com/watch?v=" + Videoid2;
                        <div class="item-video"><a class="owl-video" href="@Linkvideo2"></a></div>
                        headn += 1;
                    }
                }
            </div>
        </div>
    </div>
    <div class="VTDis-gd-title">
        <p>おすすめ動画</p>
    </div>
    <div class="card-flex">
        <div class="card-main">
            @foreach (var item in Model.Take(300))
            {

                if (item.video.status.ToString() != "missing" && n <= 99)
                {
                    var Videoid = @Html.DisplayFor(modelItem => item.video.yt_video_id).ToString();
                    var Linkphoto = "https://img.youtube.com/vi/".ToString() + Videoid + "/hqdefault.jpg";
                    var Linkvideo = "https://www.youtube.com/watch?v=".ToString() + Videoid;
                    var statue = @Html.DisplayFor(modelItem => item.video.status).ToString();

                    <div class="card-box">
                        <div class="card">
                            <a href="@Url.Action("VT_Video","JP",new { id = item.video.yt_video_id})">
                                <div class="card-img-md">
                                    <img class="card-img-top" src="@Linkphoto" alt="Card image cap">
                                </div>
                            </a>
                            <div class="card-body">
                                <a href="@Url.Action("VT_Video","JP",new { id = item.video.yt_video_id})">
                                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.video.title)</h5>
                                    <p>@Html.DisplayFor(modelItem => item.vtuber.yt_channel_name)</p>
                                    <p>@Html.DisplayFor(modelItem => item.video.published_at)</p>
                                </a>
                            </div>
                        </div>
                    </div>

                    n += 1;
                };

            }
        </div>
        <div id="d"></div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js" @*integrity="sha512-rcjfoab9cvkoh/w/t6gbbxnah5azhy4+q1exw5xeurefhbikrbq++zr+gbclo3/d3q583x/go4fkmofuhkkrda=="*@ crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var owl = $('.owl-carousel');
            owl.owlCarousel({
                videoWidth: 600,
                videoHeight: 400,
                stagePadding: 10,
                //margin: 20,
                //paddingleft: 10,
                loop: true,

                video: true,
                nav: true,
                center: true,
                dots: false,
                smartSpeed: 1000,
                responsive: {
                    300: {
                        items: 1.1,
                        videoWidth: 300,
                        videoHeight: 200,
                        nav: false
                    },
                    1200: {
                        items: 1.6
                    },
                    1500: {
                        items: 2
                    },
                    1700: {
                        items: 2.25
                    },
                    1900: {
                        items: 2.5
                    },
                    2100: {
                        items: 2.8
                    }
                }
            });
        })
    </script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>
</html>

VTWebsite/VTWebsite/Views/JP/VTWiki.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/JP/_Layout_Wiki.cshtml";
}
<title>VTuber百科 VTWiki</title>
<div>
    <div class="lay-wiki-banners"></div>
</div>

<div class="lay-wiki-purpose">
    <div class="lay-wiki-purpose-flex">
        <div class="lay-wiki-purpose-div-img">
            <img src="https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_1440,w_720,f_auto,q_auto/1369026/480076_541681.jpeg" class="lay-wiki-purpose-img" alt="Alternate Text" />
        </div>
        <div class="lay-wiki-purpose-font">
            <h3>設立の目的</h3>
            <p>
                本サイトの目的は、VTuberの2大企業である「hololive」と「rainbow society」の情報を集約することですが、VTuberライブとVTuber関連の情報を統合したサイトはありません。 これにより、初めて聴く人の数が減るのではないかと考えています。
            </p>
            <p>
                これでは、初めてVTuberを見る方の熱量が下がってしまうのではないかと考え、マルチウィンドウのライブ配信機能やVTipediaを使って動画と情報を統合し、検索コストを抑えてVTuber入門者の熱量を高め、より多くの方に業界のことを知ってもらえるようなサイトを提供していきたいと考えています。
            </p>
        </div>
    </div>
</div>


<div class="lay-wiki-function">
    <div class="lay-wiki-function-flex">
        <div class="lay-wiki-function-div-img">
            <img src="~/Photo/VTWiki-bg-middle.jpg" class="lay-wiki-purpose-img" alt="Alternate Text" />
        </div>
        <div class="lay-wiki-function-font">
            <h3>機能性と特徴</h3>
            <p>
                "VTWiki "は、大手企業2社が所有するVTuberの会社と人物のプロフィールを統合し、クローラーと埋め込み機能を使ってVTuberのTwitterアカウントから最新のニュースを取り込みます。 また、中国語、英語、日本語の言語切り替えが可能で、言語の壁によってVTuberへのアクセスが阻害される問題を解決します。
            </p>
            <p>
                また、本サイトでは、ユーザーの皆様に快適にご利用いただくために、ダークカラーを基調としたデザインを採用し、機能をすぐにご理解いただけるように簡単な紹介文を掲載しています。
            </p>
        </div>
    </div>
</div>


<div class="lay-wiki-feature">
    <div class="lay-wiki-purpose-flex">
        <div class="lay-wiki-purpose-div-img">
            <img src="~/Photo/VTWiki-bg-bottom.jpg" class="lay-wiki-purpose-img" alt="Alternate Text" />
        </div>
        <div class="lay-wiki-purpose-font">
            <h3>探索開始</h3>
            <p>
                もっと詳しく知りたい方は、ぜひご覧ください。 ライブストリーミングとVtuberのプロフィールを統合したウェブサイトです。 ウェブサイトの言語を調整したり、好みに応じて深夜モードを切り替えたりすることができます。 VTuberの最も詳しい説明は全てここにあります。
            </p>
        </div>
    </div>
</div>

VTWebsite/VTWebsite/Views/JP/VTWiki_News.cshtml
@model IEnumerable<VTWebsite.Models.Tweet_List>
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/JP/_Layout_Wiki.cshtml";
    int n = 0;
}

<title>最新ニュース VTWiki_News</title>

<header class="news-header">
    <div class="news-title">
        <h1>最新ニュース</h1>
        <h2>News</h2>
    </div>
    <div class="news-flex">

        @foreach (var item in Model)
        {
            if (n <= 98)
            {
                var twitterid = "https://twitter.com/x/status/" + @Html.DisplayFor(Modelitem => item.tweetsid).ToString();
                <div>
                    <blockquote class="twitter-tweet"><a href="@twitterid"></a></blockquote>
                </div>
                n += 1;
            }
        }
    </div>
</header>

<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
@*<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script>
    $(document).ready(function () {

        $('.grid').masonry({
            itemSelector: '.grid-item',
            columnWidth: 30%
        });

    });
</script>*@

VTWebsite/VTWebsite/Views/JP/VTWiki_People.cshtml
@model IEnumerable<VTWebsite.Models.Member_List>
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/JP/_Layout_Wiki.cshtml";
    int n = 0;

}

<title>キャラクター紹介 VTWiki_People</title>

<header class="lay-wiki-people-head">
    <div class="lay-wiki-people-head-border">
        <div class="lay-wiki-people-head-flex">
            <button class="lay-wiki-people-head-HL wiki-people-tab-btn" data-id="People_Hololive">Hololive</button>
            <button class="lay-wiki-people-head-NJ wiki-people-tab-btn" data-id="People_Nijisanji">Nijisanji</button>
        </div>
    </div>
</header>

<div class="lay-wiki-people-HL-members">
    <h1 class="lay-wiki-people-h1">Hololive</h1>
    <h1 class="lay-wiki-people-h2">Members</h1>
</div>

<div class="lay-wiki-people-NJ-members">
    <h1 class="lay-wiki-people-h1">Nijisanji</h1>
    <h1 class="lay-wiki-people-h2">Members</h1>
</div>


<section>
    @* -------------------------------------Hololive----------------------------------------- *@

    <div class="lay-wiki-people-section-flex lay-wiki-people-content lay-wiki-people-active" id="People_Hololive">

        @foreach (var item in Model)
        {
            if (item.org == "hololive")
            {

                if (n % 5 == 0)
                {
                    <div class="lay-wiki-people-section-mb">
                        @* 外距 *@
                        <a href="@Url.Action("VTWiki_Members", "JP", new { id = item.yt_channel_name, org = item.org })">
                            <div class="lay-wiki-people-section-content">
                                @* 內容 *@
                                <div class="lay-wiki-people-section-img"><img src="~/Photo/HL/@item.path" alt="Alternate Text" /></div>
                                <div class="lay-wiki-people-section-font"><span> @Html.DisplayFor(modelItem => item.yt_channel_name)</span></div>
                            </div>@* 內容 *@
                        </a>
                    </div>@* 外距 *@
                    n += 1;
                }
                else if (n % 5 == 1)
                {
                    <div class="lay-wiki-people-section-mt lay-wiki-people-PC-ml lay-wiki-people-MB-ml">
                        @* 外距 *@
                        <a href="@Url.Action("VTWiki_Members", "JP", new { id = item.yt_channel_name, org = item.org })">
                            <div class="lay-wiki-people-section-content">
                                @* 內容 *@
                                <div class="lay-wiki-people-section-img"><img src="~/Photo/HL/@item.path" alt="Alternate Text" /></div>
                                <div class="lay-wiki-people-section-font"><span> @Html.DisplayFor(modelItem => item.yt_channel_name)</span></div>
                            </div>@* 內容 *@
                        </a>
                    </div>@* 外距 *@
                    n += 1;
                }
                else if (n % 5 == 2)
                {
                    <div class="lay-wiki-people-section-mb lay-wiki-people-PC-ml">
                        @* 外距 *@
                        <a href="@Url.Action("VTWiki_Members", "JP", new { id = item.yt_channel_name, org = item.org })">
                            <div class="lay-wiki-people-section-content">
                                @* 內容 *@
                                <div class="lay-wiki-people-section-img"><img src="~/Photo/HL/@item.path" alt="Alternate Text" /></div>
                                <div class="lay-wiki-people-section-font"><span> @Html.DisplayFor(modelItem => item.yt_channel_name)</span></div>
                            </div>@* 內容 *@
                        </a>
                    </div>@* 外距 *@
                    n += 1;
                }
                else if (n % 5 == 3)
                {
                    <div class="lay-wiki-people-section-mt lay-wiki-people-PC-ml lay-wiki-people-MB-ml">
                        @* 外距 *@
                        <a href="@Url.Action("VTWiki_Members", "JP", new { id = item.yt_channel_name, org = item.org })">
                            <div class="lay-wiki-people-section-content">
                                @* 內容 *@
                                <div class="lay-wiki-people-section-img"><img src="~/Photo/HL/@item.path" alt="Alternate Text" /></div>
                                <div class="lay-wiki-people-section-font"><span> @Html.DisplayFor(modelItem => item.yt_channel_name)</span></div>
                            </div>@* 內容 *@
                        </a>
                    </div>@* 外距 *@
                    n += 1;
                }
                else if (n % 5 == 4)
                {
                    <div class="lay-wiki-people-section-mb lay-wiki-people-PC-ml">
                        @* 外距 *@
                        <a href="@Url.Action("VTWiki_Members", "JP", new { id = item.yt_channel_name, org = item.org })">
                            <div class="lay-wiki-people-section-content">
                                @* 內容 *@
                                <div class="lay-wiki-people-section-img"><img src="~/Photo/HL/@item.path" alt="Alternate Text" /></div>
                                <div class="lay-wiki-people-section-font"><span> @Html.DisplayFor(modelItem => item.yt_channel_name)</span></div>
                            </div>@* 內容 *@
                        </a>
                    </div>@* 外距 *@
                    n += 1;
                }
            }
        }

    </div>

    @* -------------------------------------Nijisanji----------------------------------------- *@

<div class="lay-wiki-people-section-flex lay-wiki-people-content" id="People_Nijisanji">

    @foreach (var item in Model)
    {
        if (item.org == "nijisanji")
        {

            if (n % 5 == 0)
            {
                <div class="lay-wiki-people-section-mb">
                    @* 外距 *@
                    <a href="@Url.Action("VTWiki_Members", "JP", new { id = item.yt_channel_name, org = item.org })">
                        <div class="lay-wiki-people-section-content">
                            @* 內容 *@
                            <div class="lay-wiki-people-section-img"><img src="~/Photo/NJ/@item.path" alt="Alternate Text" /></div>
                            <div class="lay-wiki-people-section-font"><span> @Html.DisplayFor(modelItem => item.yt_channel_name)</span></div>
                        </div>@* 內容 *@
                    </a>
                </div>@* 外距 *@
                n += 1;
            }
            else if (n % 5 == 1)
            {
                <div class="lay-wiki-people-section-mt lay-wiki-people-PC-ml lay-wiki-people-MB-ml">
                    @* 外距 *@
                    <a href="@Url.Action("VTWiki_Members", "JP", new { id = item.yt_channel_name, org = item.org })">
                        <div class="lay-wiki-people-section-content">
                            @* 內容 *@
                            <div class="lay-wiki-people-section-img"><img src="~/Photo/NJ/@item.path" alt="Alternate Text" /></div>
                            <div class="lay-wiki-people-section-font"><span> @Html.DisplayFor(modelItem => item.yt_channel_name)</span></div>
                        </div>@* 內容 *@
                    </a>
                </div>@* 外距 *@
                n += 1;
            }
            else if (n % 5 == 2)
            {
                <div class="lay-wiki-people-section-mb lay-wiki-people-PC-ml">
                    @* 外距 *@
                    <a href="@Url.Action("VTWiki_Members", "JP", new { id = item.yt_channel_name, org = item.org })">
                        <div class="lay-wiki-people-section-content">
                            @* 內容 *@
                            <div class="lay-wiki-people-section-img"><img src="~/Photo/NJ/@item.path" alt="Alternate Text" /></div>
                            <div class="lay-wiki-people-section-font"><span> @Html.DisplayFor(modelItem => item.yt_channel_name)</span></div>
                        </div>@* 內容 *@
                    </a>
                </div>@* 外距 *@
                n += 1;
            }
            else if (n % 5 == 3)
            {
                <div class="lay-wiki-people-section-mt lay-wiki-people-PC-ml lay-wiki-people-MB-ml">
                    @* 外距 *@
                    <a href="@Url.Action("VTWiki_Members", "JP", new { id = item.yt_channel_name, org = item.org })">
                        <div class="lay-wiki-people-section-content">
                            @* 內容 *@
                            <div class="lay-wiki-people-section-img"><img src="~/Photo/NJ/@item.path" alt="Alternate Text" /></div>
                            <div class="lay-wiki-people-section-font"><span> @Html.DisplayFor(modelItem => item.yt_channel_name)</span></div>
                        </div>@* 內容 *@
                    </a>
                </div>@* 外距 *@
                n += 1;
            }
            else if (n % 5 == 4)
            {
                <div class="lay-wiki-people-section-mb lay-wiki-people-PC-ml">
                    @* 外距 *@
                    <a href="@Url.Action("VTWiki_Members", "JP", new { id = item.yt_channel_name, org = item.org })">
                        <div class="lay-wiki-people-section-content">
                            @* 內容 *@
                            <div class="lay-wiki-people-section-img"><img src="~/Photo/NJ/@item.path" alt="Alternate Text" /></div>
                            <div class="lay-wiki-people-section-font"><span> @Html.DisplayFor(modelItem => item.yt_channel_name)</span></div>
                        </div>@* 內容 *@
                    </a>
                </div>@* 外距 *@
                n += 1;
            }
        }
    }



</div>
</section>

VTWebsite/VTWebsite/Views/JP/VT_Video.cshtml
@model IEnumerable<VTWebsite.Models.VideoVtuber>

@{
    Layout = "~/Views/Shared/JP/_Layout_DisIndex.cshtml";
    ViewBag.Title = "VT_Video";
    var n = 0;
    var videohid = "https://www.youtube.com/embed/".ToString() + ViewBag.msgv + "?rel=0&autoplay=1";
}

<title>ビデオページ VT_video</title>

<header class="video-header">
    <div class='video-header-yt'>
        <iframe src="@videohid"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen>
        </iframe>
    </div>
    <div class="video-header-yt-content">
        @foreach (var item in Model)
        {
            if (ViewBag.msgv == item.video.yt_video_id.ToString())
            {
                <h3>
                    @Html.DisplayFor(modelItem => item.video.title)
                </h3>
                <h4>@Html.DisplayFor(modelItem => item.video.published_at)</h4>
            }
        }
    </div>
</header>

<section>
    <div class="video-section">
        <div class="video-section-flex">
            <div class="video-secton-card-main">
                <div class="video-section-title"><p class="">エッセンスクリップ</p></div>
                @foreach (var item in Model.Take(300))
                {
                    if (item.video.status.ToString() != "missing" && n <= 99)
                    {
                        var Videoid = @Html.DisplayFor(modelItem => item.video.yt_video_id).ToString();
                        var Linkphoto = "http://img.youtube.com/vi/".ToString() + Videoid + "/hqdefault.jpg";
                        var Linkvideo = "https://www.youtube.com/watch?v=".ToString() + Videoid;
                        var name = "@Html.DisplayFor(modelItem => item.vtuber.yt_channel_name)";

                        <div class="video-section-card-box">
                            <a href="@Url.Action("VT_Video","JP",new { id = item.video.yt_video_id})"><img src="@Linkphoto" alt="@name" /></a>
                            <div class="video-section-content">
                                <div class="video-section-content-img">
                                    <img class="video-section-channel-img" src="@Html.DisplayFor(modelItem => item.vtuber.photo)" alt="Alternate Text" />
                                </div>
                                <a href="@Url.Action("VT_Video","JP",new { id = item.video.yt_video_id})" class="video-section-content-font">

                                    <h3>@Html.DisplayFor(modelItem => item.video.title)</h3>
                                    <h4>@Html.DisplayFor(modelItem => item.vtuber.yt_channel_name)</h4>
                                    <h4>@Html.DisplayFor(modelItem => item.video.published_at)</h4>

                                </a>

                            </div>
                        </div>
                        n += 1;
                    }

                }
            </div>
        </div>
    </div>
</section>